
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: lasample
  labels:
    app: hello
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello
        image: madusonovi/gitops:hellov1.2.2
        ports:
        - containerPort: 8000
